apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: example-template
  title: Example Project Template
  description: A simple template for creating a new project in Backstage.
spec:
  owner: team@example.com
  type: service
  steps:
    - id: fetch
      name: Fetch Content
      action: fetch:template
      input:
        url: ./template-repo

    - id: prepare
      name: Prepare the Project
      action: prepare:configure
      input:
        projectName: ${{ values.name }}
        projectDescription: ${{ values.description }}

  parameters:
    - title: Project Information
      properties:
        name:
          title: Project Name
          type: string
          description: The name of the new project.
        description:
          title: Project Description
          type: string
          description: A brief description of the project.

  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl }}
